### ISSUE TITLE
Mobile icon for menu missing

### ISSUE THREAD

**Issue by fabianying** [funkydan2/alpha-church#12]
On mobile, the icon for the menu seems to be missing.

See below:

![IMG_4338](https://user-images.githubusercontent.com/19388540/60094184-3d62d100-9743-11e9-9514-86e2cf7514fa.jpg)

**Comment by funkydan2** [comment]
Thanks for catching this. I won’t be able to get to this until later this week, but it shouldn’t be a hard fix. (Thoughnif you’re able to submit a PR first, that’d be great.)

**Comment by fabianying** [comment]
Thanks! I'm afraid I don't quite know how to fix it. I'm not very familiar with javascript.

(I had a look through it, though, and would be curious what the issue is. Do you need to load/import FontAwesome.css in main.scss? I couldn't find a reference to it.)

**Comment by funkydan2** [comment]
I’m not super familiar either. I’m leaving [this link](https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements#with-svg-js) to the fontawesome docs for when I get back to my Mac.

**Comment by funkydan2** [comment]
Fixed in https://github.com/funkydan2/alpha-church/commit/bf3169e169f4eeb2e91a103ecf4effd34c2f55e2
