### ISSUE TITLE
Clickable feature icon tiles

### ISSUE THREAD

**Issue by ryanclarke** [funkydan2/alpha-church#19]
I wanted to have the home page feature icons be clickable.

Proposal: an optional `url` property that will wrap the entire tile in an anchor tag.

**Comment by ryanclarke** [comment]
#18

**Comment by ryanclarke** [comment]
Hilarious. I'm obviously clueless on how to go about creating a courteous PR.

This is to notify you that I added a nice little feature and allow you to pull it in if you'd like.

**Comment by funkydan2** [comment]
No stress about GitHub courtesy - I'm a beginner with all this too!

Thanks so much for your PR - it's an elegant solution for those who want that feature! (For [my church's website](https://gympiepresbyterian.org.au) I made the text description links through the text parameter - but I like your solution better!

**Comment by ryanclarke** [comment]
I saw those links on your church site. That's what gave me the idea for this!
