### ISSUE TITLE
FA icons not working

### ISSUE THREAD

**Issue by rsouthpaw** [funkydan2/alpha-church#2]
Fa icons were working when I was using hugo version 37. When I upgraded hugo version 42, icons stopped working.

**Comment by funkydan2** [comment]
Do the icons fail only when you’re in the development environment (i.e. you run `hugo server`)?

If so, I think [this is a bug in hugo](https://github.com/gohugoio/hugo/issues/4649#issuecomment-398709258) which is effecting the way this theme loads external libraries.

**Comment by rsouthpaw** [comment]
I checked the console and I was getting following error: 

Access to CSS stylesheet at 'https://use.fontawesome.com/releases/v%!s(%3Cnil%3E)/css/all.css' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 400.

I just replaced
 
`href=\"//use.fontawesome.com/releases/v%s/css/all.css\"` 

with

`href=\"//use.fontawesome.com/releases/v5.1.0/css/all.css\"`

Now icons are working!
