### ISSUE TITLE
Can't get contact form to work, demo site isn't working either

### ISSUE THREAD

**Issue by drupalninja** [funkydan2/alpha-church#25]
I have tried getting this to work a variety of ways on my own instance and have not figured it out.

I also see the Contact form does not appear on the demo:
https://themes.gohugo.io//theme/alpha-church/contact

**Comment by funkydan2** [comment]
Do you have [inline shortcodes enabled](https://gohugo.io/templates/shortcode-templates/#inline-shortcodes)?

That's what was wrong on the example site. It's now fixed, and the documentation has been updated. (The theme gallery will be updated the next time on the next build schedule.)

**Comment by drupalninja** [comment]
Ah okay, I didn't realize that was something I needed to do. Still getting used to Hugo. This is a great theme, thanks!
