### ISSUE TITLE
exampleSite fails to render due to (erroneous?) "theme = ["../.."]" in config.toml

### ISSUE THREAD

**Issue by anthonyfok** [funkydan2/alpha-church#3]
Hi @funkydan2,

Thank you for creating and maintaining probably the very first Hugo theme dedicated for use by churches.  :-)

You might have noticed that the [Demo] button at https://themes.gohugo.io/alpha-church/ disappeared about two weeks ago.  That is partially my doing; please see gohugoio/hugo#5061 for the background and suggested fix.

Sorry for my tardiness in reaching out to you.  I had been very busy somewhat unexpectedly and I am still trying to catch up to a lot of things, so please forgive me for not providing a PR directly.

**Comment by funkydan2** [comment]
Thanks for pointing this out @anthonyfok. I'd noticed something wasn't right (as per [this issue](https://github.com/gohugoio/hugo/issues/4649#issuecomment-398709258)) but hadn't been able to track anything down. 

I've committed a change where I've fixed the `themesDir` and `theme` settings for the example site. It looks like it's now working for me.
