### ISSUE TITLE
meta description, meta keywords and tags

### ISSUE THREAD

**Issue by diekloope** [funkydan2/alpha-church#31]
I tried to set the meta description, keywords and tag vaules in the config.toml. But the values are not available in die public files. How van I set the values in the config.toml for using and generating in the public files?

**Comment by funkydan2** [comment]
The meta description is used in the `<head>` section of the HTML file. I've checked and it's working.

At the moment the theme doesn't put keywords or tags in a `<meta name="keywords">` section in `<head>`.

How would you like that to be supported? I'm thinking we could have keywords from the site configuration put in the home page, and then use tags from pages for content pages.

**Comment by diekloope** [comment]
Yes, i think that is a good solution. Thanks for your support.
