### ISSUE TITLE
Broken on Hugo v0.82.0

### ISSUE THREAD

**Issue by anakinkinsey** [funkydan2/alpha-church#33]
Not sure if you plan on updating this with new hugo versions, but on the recently released version `hugo` breaks with errors 
```ERROR 2021/03/22 21:37:00 render of "section" failed: execute of template failed: template: _default/list.html:1:3: executing "_default/list.html" at <partial "header" . .Section "list">: error calling partial: "/themes/alpha-church/layouts/partials/header.html:21:100": execute of template failed: template: partials/header.html:21:100: executing "partials/header.html" at <.MediaType.Suffix>: can't evaluate field Suffix in type media.Type```
From the [hugo changelog](https://github.com/gohugoio/hugo/releases/tag/v0.82.0)  it looks like mediaType has been changed

**Comment by funkydan2** [comment]
Already fixed in [this commit](https://github.com/funkydan2/alpha-church/commit/f28866b1395e1abc7beaec3f69db250f15c7ec20#diff-849b12775c618f03de30403aa236f73e6fa9ee05bc0cd078f04df6aa81633460) and [this release](https://github.com/funkydan2/alpha-church/releases/tag/20210322).

**Comment by anakinkinsey** [comment]
Ahh, I should have made sure my version was up to date! Thanks!
