### ISSUE TITLE
Allow using an image for the nav bar

### ISSUE THREAD

**Issue by Hona** [funkydan2/alpha-church#35]
I'm in the process of using the theme, and made a CSS hack to replace the text in the nav bar with an image - but for other people trying to use this theme it might be nice to allow an image/text.

An example of my modifications:
![image](https://user-images.githubusercontent.com/10430890/117598580-6b146000-b18b-11eb-916d-f45f286fad8b.png)

**Comment by funkydan2** [comment]
Looks nice. If you're able to provide a PR, I'd be happy to review and include.

**Comment by ajithjose** [comment]
Hi Daniel, I'm also facing the same requirement. Could you please add a change to include a responsive logo on the navigation bar? Thanks

**Comment by ajithjose** [comment]
@funkydan2 By any chance do you have an update on this? Thanks

**Comment by funkydan2** [comment]
Hi @ajithjose, I haven't given any thought to this idea as at the moment it's not something I'm looking at for my use of this theme. Although it's not a significant change, it'd take a bit of work with both the CSS and templating, time which I don't have at the moment.

However, as I said previously if you could work out how you think this would be best implemented and could provide a PR, I'd be very happy to review and accept.
