### ISSUE TITLE
Localization of contact page

### ISSUE THREAD

**Issue by whiver** [funkydan2/alpha-church#41]
Hi :)

Looking at the contact page (contact.html partial), it seems the strings are hardcoded in the theme, therefore it cannot be replaced without overriding the partial. That would be cool to have it as a parameter for translation purpose.

Thanks for your work!

**Comment by funkydan2** [comment]
Good point. Does commit https://github.com/funkydan2/alpha-church/commit/24df064b9b2fef6e5af155241b07846e70f4925a do what you're thinking?

**Comment by whiver** [comment]
It seems so good job! :) Should we propose pull requests to add translations or is it possible to override this file in the site folder?

**Comment by funkydan2** [comment]
Both are good ideas.

If you make a translation file, submit a PR and I’d be happy to merge.

But the beauty of Hugo is how easy it is to extend themes (if they’re built well). All you’ll need to do is put your own translation into the `/i18n` (In the root of your site, not the `theme` directory) and you'll be able to personalise your site (you'll also need to set the language in the config file).

**Comment by whiver** [comment]
Alright, thanks for your answer and quick resolution @funkydan2 :)
