### ISSUE TITLE
Why is the "images" frontmatter param an array

### ISSUE THREAD

**Issue by whiver** [funkydan2/alpha-church#42]
Hi!

Just wondered why the `images` param in the frontmatter is an array, as only the first entry seems to be used anyway?
It makes editing it a bit more tedious when using netlify-cms, and it's not obvious to the content writers that only the first image is useful in the list...

Thanks! :)

**Comment by funkydan2** [comment]
It's a good question. I think it's so the variable is compatible with the built-in social media 'cards' template: https://gohugo.io/templates/internal#twitter-cards.

**Comment by whiver** [comment]
I see, I'll live with that then :) Thanks for your answer!
