### ISSUE TITLE
Found error in hugo.toml 

### ISSUE THREAD

**Issue by johnwuelk** [funkydan2/alpha-church#54]
in the hugo.toml file `[security]` is missing above the following line: 
`enableInlineShortcodes = true`

When this is missing, the contact form in the Contact page will not show up,  as the template code in the markdown is not  rendered.

**Comment by funkydan2** [comment]
That's interesting - because it seems to work without that even though the [hugo documents say precisely that!](https://gohugo.io/templates/shortcode/#inline-shortcodes)

Will fix soon—thanks!
