### ISSUE TITLE
Formspree Setup

### ISSUE THREAD

**Issue by ortonvillefarmersmarket** [funkydan2/alpha-church#7]
I am having trouble setting up formspree

I have modified the contact settings in config.toml like so:
service = "formspree"
    confirm_page = "/contact_thanks"
    formspree_email="ortonvillefarmersmarket@gmail.com"

And then sent a test email form my contact form - this takes me to the formspree homepage.

What other steps are required to setup that I am missing?

**Comment by ortonvillefarmersmarket** [comment]
I hardcoded my email into contact.html, and that worked. Looks like there is an issue with pulling the email in from config.toml

**Comment by funkydan2** [comment]
Well spotted. I haven't tested the formspree integration, but I've now changed something which should mean the email is pulled from config.toml.

Can you please update to the latest version of the theme and let me know if it now works?

**Comment by ortonvillefarmersmarket** [comment]
Looks like it worked! Thanks for the quick response
